### ISSUE TITLE
Doesn't work, no messages

### ISSUE THREAD

**Issue by andreamattioli** [konstantinkobs/brackets-colorHints#5]
Hi, thanks for your work on this good extension. I'm sorry, but in my Brackets (1.3.0-16022) it's not working and I haven't messages to show.
I have a lot of extensions, maybe that's the problem..

**Comment by Madebym** [comment]
Doesn't work for me either. Exact build like @andreamattioli .

**Comment by Wikunia** [comment]
Hi @andreamattioli ,

sorry for the late response. Would be great if you can copy all your other extensions into the `disabled` folder and then try it again. 

Thanks for the issue!

**Comment by andreamattioli** [comment]
I've tried, closed and reopened (not refresh with f5), same result.

**Comment by Wikunia** [comment]
So all disabled doesn't work as well? Do you have errors in the Developer Tools? (F12)

**Comment by andreamattioli** [comment]
No errors, but I've noticed that it doesn't work only inside media queries, outside it's all ok.

**Comment by Wikunia** [comment]
Thanks @andreamattioli can you provide a quick example?

**Comment by andreamattioli** [comment]
```CSS
.projects-credits {
  background-color: #123;
}
.text-color1 a {
  color: #123; <------ HINT
}
@media (min-width: 769px) {
  .text-color1 a {
    color: #123; <------ NO HINT
  }
}
```
